[tool.anki-addon-release]
target = "deck"

[tool.anki-addon-release.ankiweb]
shared_id = "590256847"
listing_file = "release/turkey.md"
login_email_env = "ANKIWEB_EMAIL"
login_password_env = "ANKIWEB_PASSWORD"

[tool.anki-addon-release.deck]
source_deck_id_env = "ANKIWEB_SOURCE_DECK_ID_TURKEY_REGIONS"
